src/java/InterdisciplinarAPI/ProfessoresController.java
package InterdisciplinarAPI;

import InterdisciplinarMDL.Professores;
import InterdisciplinarAPI.util.JsfUtil;
import InterdisciplinarAPI.util.JsfUtil.PersistAction;
import InterdisciplinarCL.ProfessoresFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("professoresController")
@SessionScoped
public class ProfessoresController implements Serializable {

    @EJB
    private InterdisciplinarCL.ProfessoresFacade ejbFacade;
    private List<Professores> items = null;
    private Professores selected;

    public ProfessoresController() {
    }

    public Professores getSelected() {
        return selected;
    }

    public void setSelected(Professores selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ProfessoresFacade getFacade() {
        return ejbFacade;
    }

    public Professores prepareCreate() {
        selected = new Professores();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("ProfessoresCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("ProfessoresUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("ProfessoresDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Professores> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Professores getProfessores(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Professores> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Professores> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Professores.class)
    public static class ProfessoresControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ProfessoresController controller = (ProfessoresController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "professoresController");
            return controller.getProfessores(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Professores) {
                Professores o = (Professores) object;
                return getStringKey(o.getIdpessoa());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Professores.class.getName()});
                return null;
            }
        }

    }

}

web/view/professores/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ProfessoresCreateDlg" widgetVar="ProfessoresCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateProfessoresTitle}">
            <h:form id="ProfessoresCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{professoresController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateProfessoresLabel_idpessoa}" for="idpessoa" />
                        <p:inputText id="idpessoa" value="#{professoresController.selected.idpessoa}" title="#{bundle.CreateProfessoresTitle_idpessoa}" required="true" requiredMessage="#{bundle.CreateProfessoresRequiredMessage_idpessoa}"/>
                        <p:outputLabel value="#{bundle.CreateProfessoresLabel_formacao}" for="formacao" />
                        <p:inputText id="formacao" value="#{professoresController.selected.formacao}" title="#{bundle.CreateProfessoresTitle_formacao}" />
                        <p:outputLabel value="#{bundle.CreateProfessoresLabel_pessoas}" for="pessoas" />
                        <p:selectOneMenu id="pessoas" value="#{professoresController.selected.pessoas}" required="true" requiredMessage="#{bundle.EditProfessoresRequiredMessage_pessoas}">
                            <f:selectItems value="#{pessoasController.itemsAvailableSelectOne}"
                                           var="pessoasItem"
                                           itemValue="#{pessoasItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{professoresController.create}" value="#{bundle.Save}" update="display,:ProfessoresListForm:datalist,:growl" oncomplete="handleSubmit(args,'ProfessoresCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ProfessoresCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/view/professores/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ProfessoresEditDlg" widgetVar="ProfessoresEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditProfessoresTitle}">
            <h:form id="ProfessoresEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{professoresController.selected != null}">
                        <p:outputLabel value="#{bundle.EditProfessoresLabel_idpessoa}" for="idpessoa" />
                        <p:inputText id="idpessoa" value="#{professoresController.selected.idpessoa}" title="#{bundle.EditProfessoresTitle_idpessoa}" required="true" requiredMessage="#{bundle.EditProfessoresRequiredMessage_idpessoa}"/>
                        <p:outputLabel value="#{bundle.EditProfessoresLabel_formacao}" for="formacao" />
                        <p:inputText id="formacao" value="#{professoresController.selected.formacao}" title="#{bundle.EditProfessoresTitle_formacao}" />
                        <p:outputLabel value="#{bundle.EditProfessoresLabel_pessoas}" for="pessoas" />
                        <p:selectOneMenu id="pessoas" value="#{professoresController.selected.pessoas}" required="true" requiredMessage="#{bundle.EditProfessoresRequiredMessage_pessoas}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{pessoasController.itemsAvailableSelectOne}"
                                           var="pessoasItem"
                                           itemValue="#{pessoasItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{professoresController.update}" value="#{bundle.Save}" update="display,:ProfessoresListForm:datalist,:growl" oncomplete="handleSubmit(args, 'ProfessoresEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ProfessoresEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/view/professores/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListProfessoresTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="ProfessoresListForm">
                <p:panel header="#{bundle.ListProfessoresTitle}">
                    <p:dataTable id="datalist" value="#{professoresController.items}" var="item"
                                 selectionMode="single" selection="#{professoresController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idpessoa}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListProfessoresTitle_idpessoa}"/>
                            </f:facet>
                            <h:outputText value="#{item.idpessoa}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListProfessoresTitle_formacao}"/>
                            </f:facet>
                            <h:outputText value="#{item.formacao}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListProfessoresTitle_pessoas}"/>
                            </f:facet>
                            <h:outputText value="#{item.pessoas}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{professoresController.prepareCreate}" update=":ProfessoresCreateForm" oncomplete="PF('ProfessoresCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":ProfessoresViewForm" oncomplete="PF('ProfessoresViewDialog').show()" disabled="#{empty professoresController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":ProfessoresEditForm" oncomplete="PF('ProfessoresEditDialog').show()" disabled="#{empty professoresController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{professoresController.destroy}" update=":growl,datalist" disabled="#{empty professoresController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/view/professores/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ProfessoresViewDlg" widgetVar="ProfessoresViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewProfessoresTitle}">
            <h:form id="ProfessoresViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{professoresController.selected != null}">
                        <h:outputText value="#{bundle.ViewProfessoresLabel_idpessoa}"/>
                        <h:outputText value="#{professoresController.selected.idpessoa}" title="#{bundle.ViewProfessoresTitle_idpessoa}"/>
                        <h:outputText value="#{bundle.ViewProfessoresLabel_formacao}"/>
                        <h:outputText value="#{professoresController.selected.formacao}" title="#{bundle.ViewProfessoresTitle_formacao}"/>
                        <h:outputText value="#{bundle.ViewProfessoresLabel_pessoas}"/>
                        <h:outputText value="#{professoresController.selected.pessoas}" title="#{bundle.ViewProfessoresTitle_pessoas}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="ProfessoresViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>